[package]
name = "io-mux"
version = "0.1.0"
authors = ["Josh Triplett <josh@joshtriplett.org>"]
description = "Provide multiple file descriptors writing into one in-order pipe, tagged by the source of data (e.g. stdout/stderr)"
keywords = ["log", "pipe", "stdout", "stderr"]
categories = ["command-line-interface"]
repository = "https://github.com/joshtriplett/io-mux"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
libc = "0.2.66"
tempfile = "3.1"
